language: python
sudo: false

env:
- TOXENV=py38
- TOXENV=py39
- TOXENV=py310

install:
- pip install virtualenv tox docutils coveralls

script:
- python setup.py test
- python setup.py check -r

after_success:
- coveralls
